#!/usr/bin/env python3

import os
import yaml
import sys
import shlex

if __name__ == '__main__':

    own_path = os.path.abspath(__file__)
    base_dir = os.path.dirname(own_path)
    print(f"base_dir: {base_dir}")

    if len(sys.argv) == 2:
        config_path = sys.argv[1]
    else:
        config_path = os.path.join(base_dir, 'etc', 'pkgtst.yaml')

    var_path = os.path.join(base_dir, 'var')
    ct_path = os.path.join(var_path, 'custom_test')

    dirs = [
        os.path.join(base_dir, 'var'),
        os.path.join(base_dir, 'var', 'db'),
        os.path.join(base_dir, 'var', 'custom_test'),
        os.path.join(base_dir, 'var', 'custom_test', 'scripts'),
        os.path.join(base_dir, 'var', 'custom_test', 'output'),
        os.path.join(base_dir, 'var', 'custom_test', 'results'),
        os.path.join(base_dir, 'var', 'log'),
        os.path.join(base_dir, 'var', 'log', 'arrays'),
        os.path.join(base_dir, 'var', 'log', 'tests'),
        os.path.join(base_dir, 'var', 'log', 'render_jobs'),
        os.path.join(base_dir, 'reports')
    ]

    for d in dirs:
        if os.path.exists(d):
            sys.stdout.write(f"The directory {shlex.quote(d)} already exists\n")
        else:
            os.mkdir(d)
            sys.stdout.write(f"Created {shlex.quote(d)}\n")

    fp = open(config_path, 'r')
    config_data = yaml.safe_load(fp)
    
    config_data['fileint']['dbfile'] = os.path.join(base_dir, 'var', 'db', 'fileint.sql')
    config_data['report_gen']['dbfile'] = os.path.join(base_dir, 'var', 'db', 'results.sql')
    config_data['report_gen']['rendered_html'] = os.path.join(base_dir, 'reports', 'results.html')
    config_data['custom_test']['script_dir'] = os.path.join(base_dir, 'var', 'custom_test', 'scripts')
    config_data['custom_test']['output_dir'] = os.path.join(base_dir, 'var', 'custom_test', 'output')
    config_data['custom_test']['results_dir'] = os.path.join(base_dir, 'var', 'custom_test', 'results')
    config_data['slurm_runner']['output_dir'] = os.path.join(base_dir, 'var', 'log')

    with open(config_path, 'w') as fp:
        yaml.dump(config_data, fp, default_flow_style=False)

    sys.stdout.write(f"Set paths in {config_path}\n")
